### ISSUE TITLE
CRUD modularity UX/UI design

### ISSUE THREAD

**Issue by jarrodek** [api-modeling/domain-modeler#3]
- [x] - add a module
- [x] - edit a module
- [x] - visualize modules
- [x] - delete a module

TODO:
- flow of deleting a module that has sub-modules / models

**Comment by jarrodek** [comment]
To be discussed:
- What happens when we want to remove a module and it contains modules / models? Should it be delete as well? Should an UI ask to confirm if the module is not empty?
- Should we allow to move module from one module to another (drag and drop)? What happens to the namespace and ids then?
- What happens when the name of the module change? Should namespace / id of objects inside it change?

**Comment by KellyHenvy** [comment]
> To be discussed:
> 
> * What happens when we want to remove a module and it contains modules / models? Should it be delete as well? Should an UI ask to confirm if the module is not empty?

_-The UI should ask before and give an option to move the contents to a different grouping
 but if the module is the highest level grouping then I also want to be able to delete it with all of its contents_ 

> * Should we allow to move module from one module to another (drag and drop)? What happens to the namespace and ids then?

_-I think we need to better define the levels to allow for both structure and flexibility - IMO there should be a highest level grouping that subgroups and models belong to, and that you should be able to move subgroups and models as needed or organize them._ 

> * What happens when the name of the module change? Should namespace / id of objects inside it change?

_-there are many use cases where a modeler will be creating their taxonomy as best they can at the time, but continues to iterate and find more appropriate places for those objects as they continue and will need (at least the ids) of them to not change based on their movement_
