### ISSUE TITLE
Create a schema for the domain modeling story

### ISSUE THREAD

**Issue by jarrodek** [api-modeling/domain-modeler#35]
Design a schema to be visualized in the domain modeling story.

This should not be very precise as most of properties won't be visualized. We need a list of entities in the domain (after importing it to the app you will see just a flat list of entities). 
Then we need to decide which one we will visualize in details and for these we need detailed structure:
- attributes
- associations

Then for FIHR mapping which properties will be mapped to which FIHR properties.

**Comment by KellyHenvy** [comment]
FHIR piece to import: http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient

Will capture the mappings and the other example source schema in a gsheet :)
